apt install -y 0verkill
apt install -y 2048-c
apt install -y 2ping
apt install -y 6tunnel
apt install -y 7zip
apt install -y 8086tiny
apt install -y a52dec
apt install -y aalib-static
apt install -y aalib
apt install -y aapt2
apt install -y aapt
apt install -y abduco
apt install -y abook
apt install -y abootimg
apt install -y abseil-cpp
apt install -y ack-grep
apt install -y acr
apt install -y adms
apt install -y aerc
apt install -y agate
apt install -y age
apt install -y agg
apt install -y aha
apt install -y aichat
apt install -y aidl
apt install -y alass
apt install -y alembic
apt install -y algernon
apt install -y alist
apt install -y alpine
apt install -y alsa-lib
apt install -y alsa-plugins
apt install -y alsa-utils-static
apt install -y alsa-utils
apt install -y amber
apt install -y amfora
apt install -y android-tools
apt install -y anewer
apt install -y angband
apt install -y angle-android
apt install -y angle-grinder
apt install -y ani-cli
apt install -y ansifilter
apt install -y ant
apt install -y antibody
apt install -y antiword
apt install -y aom-tools
apt install -y apache-orc
apt install -y apache2
apt install -y apkeep
apt install -y apksigner
apt install -y appstream
apt install -y apr-static
apt install -y apr-util-static
apt install -y apr-util
apt install -y apr
apt install -y apt-file
apt install -y apt-ftparchive
apt install -y apt-transport-tor
apt install -y apt
apt install -y aptly
apt install -y argon2-static
apt install -y argon2
apt install -y argp-static
apt install -y argp
apt install -y aria2
apt install -y arj
apt install -y arpack-ng
apt install -y artalk
apt install -y arturo
apt install -y asciidoc
apt install -y asciidoctor
apt install -y asciinema
apt install -y asm-lsp
apt install -y aspell-de
apt install -y aspell-en
apt install -y aspell-es
apt install -y aspell-fr
apt install -y aspell-static
apt install -y aspell
apt install -y aspnetcore-runtime-8.0
apt install -y aspnetcore-runtime-dbg-8.0
apt install -y aspnetcore-targeting-pack-8.0
apt install -y assimp
apt install -y astra-sm
apt install -y asymptote
apt install -y at-spi2-core
apt install -y at
apt install -y atomicparsley
apt install -y atomvm
apt install -y atool
apt install -y attr-static
apt install -y attr
apt install -y atuin
apt install -y aubio-static
apt install -y aubio
apt install -y autoconf-archive
apt install -y autoconf213
apt install -y autoconf
apt install -y autojump
apt install -y automake
apt install -y autossh
apt install -y aview
apt install -y avra
apt install -y await
apt install -y awesomeshot
apt install -y axel
apt install -y b3sum
apt install -y babl
apt install -y bacula-fd-static
apt install -y bacula-fd
apt install -y badvpn-udpgw
apt install -y barcode
apt install -y base16384
apt install -y bash-completion
apt install -y bash
apt install -y bastet
apt install -y bat
apt install -y bc-gh
apt install -y bc
apt install -y bcal
apt install -y bdsup2sub
apt install -y beanshell
apt install -y bed
apt install -y below
apt install -y bftpd
apt install -y bgrep
apt install -y binaryen
apt install -y binutils-bin
apt install -y binutils-cross
apt install -y binutils-gold
apt install -y binutils-is-llvm
apt install -y binutils-libs
apt install -y binutils
apt install -y bison-static
apt install -y bison
apt install -y bitcoin
apt install -y bitlbee
apt install -y bk
apt install -y blackbox
apt install -y blade
apt install -y blas-openblas
apt install -y blink
apt install -y blk-utils
apt install -y blogc
apt install -y bmon
apt install -y boinc
apt install -y boinctui
apt install -y bombadillo
apt install -y boost-headers
apt install -y boost-static
apt install -y boost
apt install -y bore
apt install -y borgbackup
apt install -y botan3-static
apt install -y botan3
apt install -y boxes
apt install -y brainfuck-static
apt install -y brainfuck
apt install -y brogue
apt install -y brook
apt install -y broot
apt install -y brotli
apt install -y bsd-finger
apt install -y bsd-games
apt install -y bsdtar
apt install -y btfs2
apt install -y buf
apt install -y build-essential
apt install -y busybox
apt install -y bvi
apt install -y byacc
apt install -y byobu
apt install -y bzip2
apt install -y c-ares
apt install -y c-script
apt install -y c-toxcore-static
apt install -y c-toxcore
apt install -y ca-certificates-java
apt install -y ca-certificates
apt install -y cabextract
apt install -y cabin
apt install -y cadaver
apt install -y caddy
apt install -y calc
apt install -y calcurse-caldav
apt install -y calcurse
apt install -y capnproto
apt install -y capstone-static
apt install -y capstone
apt install -y cargo-c
apt install -y catdoc
apt install -y catgirl
apt install -y catimg
apt install -y cava
apt install -y cavez-of-phear
apt install -y cavif-rs
apt install -y cboard
apt install -y cbonsai
apt install -y cc65
apt install -y ccache
apt install -y cccc
apt install -y ccextractor
apt install -y ccls
apt install -y ccrypt
apt install -y cec-client
apt install -y ceu-lang
apt install -y cfengine-static
apt install -y cfengine
apt install -y cfm
apt install -y cgal
apt install -y cgdb
apt install -y cgif
apt install -y chafa-static
apt install -y chafa
apt install -y check-static
apt install -y check
apt install -y chezmoi
apt install -y chicken-static
apt install -y chicken
apt install -y choose
apt install -y chromaprint
apt install -y chrony
apt install -y cicada
apt install -y ciso
apt install -y ckermit
apt install -y clamav-static
apt install -y clamav
apt install -y clang
apt install -y clblast
apt install -y cliaoke
apt install -y clidle
apt install -y clifm
apt install -y clinfo
apt install -y clipp
apt install -y cloneit
apt install -y cloudflared
apt install -y clpeak
apt install -y clvk
apt install -y cmake-curses-gui
apt install -y cmake
apt install -y cmark-static
apt install -y cmark
apt install -y cmatrix
apt install -y cmocka
apt install -y cmus
apt install -y cmusfm
apt install -y codecrypt
apt install -y coinor-cbc-static
apt install -y coinor-cbc
apt install -y coinor-clp-static
apt install -y coinor-clp
apt install -y cointop
apt install -y colm-static
apt install -y colm
apt install -y colordiff
apt install -y command-not-found
apt install -y composer
apt install -y console-bridge
apt install -y convertlit
apt install -y cookcli
apt install -y coreutils
apt install -y corgi
apt install -y corkscrew
apt install -y cowsay
apt install -y cpio
apt install -y cppcheck
apt install -y cppi
apt install -y cpufetch
apt install -y cpulimit
apt install -y crawl
apt install -y croc
apt install -y cronie
apt install -y crowbook
apt install -y crunch
apt install -y crypto-monitor
apt install -y cryptopp-static
apt install -y cryptopp
apt install -y crystal
apt install -y cscope
apt install -y csol
apt install -y csview
apt install -y ctags
apt install -y ctypes-sh
apt install -y cuetools
apt install -y cups-pdf
apt install -y cups-static
apt install -y cups
apt install -y curl
apt install -y curlie
apt install -y curseofwar
apt install -y cvs
apt install -y d8
apt install -y daemonize
apt install -y dar-static
apt install -y dar
apt install -y darkhttpd
apt install -y dart
apt install -y dasel
apt install -y dash
apt install -y dasm
apt install -y datamash
apt install -y dateutils
apt install -y db
apt install -y dbus-python
apt install -y dbus-static
apt install -y dbus
apt install -y dcmtk
apt install -y dcraw
apt install -y ddrescue
apt install -y debianutils
apt install -y debootstrap
apt install -y delve
apt install -y desed
apt install -y deutex
apt install -y dex2jar
apt install -y dialog-static
apt install -y dialog
apt install -y dictd
apt install -y diffstat
apt install -y difftastic
apt install -y diffutils
apt install -y dirb
apt install -y direnv
apt install -y direvent
apt install -y discordo
apt install -y diskus
apt install -y distant
apt install -y distcc
apt install -y djvulibre-static
apt install -y djvulibre
apt install -y dmagnetic
apt install -y dmtx-utils
apt install -y dnote-server
apt install -y dnote
apt install -y dns2tcp
apt install -y dnslookup
apt install -y dnsmap
apt install -y dnstop
apt install -y dnsutils-static
apt install -y dnsutils
apt install -y docbook-xml
apt install -y docbook-xsl
apt install -y docopt-static
apt install -y docopt
apt install -y doctest
apt install -y doge
apt install -y dopewars
apt install -y dos2unix
apt install -y dosfstools
apt install -y dotconf-static
apt install -y dotconf
apt install -y dotnet-apphost-pack-8.0
apt install -y dotnet-host-8.0
apt install -y dotnet-host
apt install -y dotnet-hostfxr-8.0
apt install -y dotnet-runtime-8.0
apt install -y dotnet-runtime-dbg-8.0
apt install -y dotnet-sdk-8.0
apt install -y dotnet-sdk-dbg-8.0
apt install -y dotnet-targeting-pack-8.0
apt install -y dotnet-templates-8.0
apt install -y dotnet8.0
apt install -y double-conversion
apt install -y doxygen
apt install -y dpkg-perl
apt install -y dpkg-scanpackages
apt install -y dpkg
apt install -y dropbear
apt install -y dtach
apt install -y dtc-static
apt install -y dtc
apt install -y dte
apt install -y dua
apt install -y duc
apt install -y duckdb
apt install -y duf
apt install -y dufs
apt install -y duktape
apt install -y dust
apt install -y dvdauthor
apt install -y dvtm
apt install -y dwarves
apt install -y dx
apt install -y e2fsprogs
apt install -y e2tools
apt install -y ebook-tools
apt install -y ecj
apt install -y ecl
apt install -y ed
apt install -y editorconfig-core-c-static
apt install -y editorconfig-core-c
apt install -y eigen
apt install -y eja
apt install -y electric-fence-static
apt install -y electric-fence
apt install -y electrum
apt install -y elfutils
apt install -y elinks
apt install -y elixir
apt install -y eltclsh
apt install -y elvish
apt install -y emacs
apt install -y emscripten-binaryen
apt install -y emscripten-llvm
apt install -y emscripten-tests-third-party
apt install -y emscripten
apt install -y enblend
apt install -y enchant-static
apt install -y enchant
apt install -y enscript
apt install -y entr
apt install -y erlang
apt install -y esbuild
apt install -y espeak-static
apt install -y espeak
apt install -y et
apt install -y etsh
apt install -y exercism
apt install -y exhale
apt install -y exiftool
apt install -y exiv2
apt install -y expect
apt install -y eza
apt install -y fact++
apt install -y fakeroot-static
apt install -y fakeroot
apt install -y fasd
apt install -y fastfetch
apt install -y fastmod
apt install -y fatsort
apt install -y faust-static
apt install -y faust
apt install -y faustlibraries
apt install -y fclones
apt install -y fcp
apt install -y fd
apt install -y fdisk
apt install -y fdkaac
apt install -y fdm
apt install -y fdroidcl
apt install -y fdupes
apt install -y fennel
apt install -y feroxbuster
apt install -y fetchmail
apt install -y fff
apt install -y ffmpeg
apt install -y ffmpegthumbnailer
apt install -y ffsend
apt install -y fftw-static
apt install -y fftw
apt install -y figlet
apt install -y file-static
apt install -y file
apt install -y finch-static
apt install -y finch
apt install -y findomain
apt install -y findutils
apt install -y fish
apt install -y flac
apt install -y flang
apt install -y flatbuffers-static
apt install -y flatbuffers
apt install -y flex-static
apt install -y flex
apt install -y fluidsynth
apt install -y flyctl
apt install -y fm
apt install -y fmt
apt install -y fontconfig-static
apt install -y fontconfig-utils
apt install -y fontconfig
apt install -y forestdb-dump
apt install -y forgejo
apt install -y fortune
apt install -y fossil
apt install -y freecolor
apt install -y freeimage-static
apt install -y freeimage
apt install -y freetype-static
apt install -y freetype
apt install -y frei0r-plugins
apt install -y fribidi-static
apt install -y fribidi
apt install -y frobtads
apt install -y frogcomposband
apt install -y frotz
apt install -y frp
apt install -y fselect
apt install -y fsmon
apt install -y fwknop-static
apt install -y fwknop
apt install -y fx
apt install -y fzf
apt install -y fzy
apt install -y g-ir-scanner
apt install -y game-music-emu
apt install -y gap-packages
apt install -y gap
apt install -y gatling
apt install -y gauche-static
apt install -y gauche
apt install -y gawk-static
apt install -y gawk
apt install -y gbt
apt install -y gcal
apt install -y gdal
apt install -y gdb
apt install -y gdbm-static
apt install -y gdbm
apt install -y gdbserver
apt install -y gdk-pixbuf
apt install -y gdrive-downloader
apt install -y gdu
apt install -y geckodriver
apt install -y gecode-static
apt install -y gecode
apt install -y gegl
apt install -y gengetopt
apt install -y geographiclib
apt install -y geoip2-database
apt install -y germanium
apt install -y getconf
apt install -y geth-utils
apt install -y geth
apt install -y gettext-static
apt install -y gettext
apt install -y gexiv2
apt install -y gflags-static
apt install -y gflags
apt install -y gforth
apt install -y gh
apt install -y ghostscript
apt install -y giflib-static
apt install -y giflib-utils
apt install -y giflib
apt install -y gifsicle
apt install -y gifski
apt install -y git-crypt
apt install -y git-delta
apt install -y git-lfs
apt install -y git-sizer
apt install -y git-svn
apt install -y git
apt install -y gitea
apt install -y gitflow-avh
apt install -y gitoxide
apt install -y gitui
apt install -y gkermit
apt install -y glab-cli
apt install -y gleam
apt install -y glib-bin
apt install -y glib-cross
apt install -y glib-networking
apt install -y glib
apt install -y glm
apt install -y global
apt install -y glow
apt install -y glpk-static
apt install -y glpk
apt install -y glslang
apt install -y gluelang
apt install -y glulxe
apt install -y gmic-gm
apt install -y gmic
apt install -y gn
apt install -y gnucap
apt install -y gnuchess
apt install -y gnucobol-static
apt install -y gnucobol
apt install -y gnugo
apt install -y gnuit
apt install -y gnunet-static
apt install -y gnunet
apt install -y gnupg
apt install -y gnuplot
apt install -y gnurl-static
apt install -y gnurl
apt install -y gnushogi
apt install -y gnuski
apt install -y gnustep-make
apt install -y gnutls
apt install -y go-findimagedupes
apt install -y go-musicfox
apt install -y goaccess
apt install -y gobang
apt install -y gobject-introspection
apt install -y gogs
apt install -y gojq
apt install -y golang-doc
apt install -y golang
apt install -y gomp
apt install -y gomuks
apt install -y google-drive-upload
apt install -y google-glog
apt install -y googletest
apt install -y goose
apt install -y gopass
apt install -y gopher
apt install -y gopls
apt install -y gotop
apt install -y gotty
apt install -y gpac-static
apt install -y gpac
apt install -y gperf
apt install -y gpgme-static
apt install -y gpgme
apt install -y gpgmepp-static
apt install -y gpgmepp
apt install -y gpgv
apt install -y gping
apt install -y gpsbabel
apt install -y gradle
apt install -y grafana
apt install -y graphene
apt install -y graphicsmagick-static
apt install -y graphicsmagick
apt install -y graphviz-static
apt install -y graphviz
apt install -y greed
apt install -y grep
apt install -y grex
apt install -y groff
apt install -y gron
apt install -y groonga
apt install -y groovy
apt install -y gsasl
apt install -y gsf-tools
apt install -y gsl-static
apt install -y gsl
apt install -y gst-libav
apt install -y gst-plugins-bad
apt install -y gst-plugins-base
apt install -y gst-plugins-gl-headers
apt install -y gst-plugins-good
apt install -y gst-plugins-ugly
apt install -y gst-python
apt install -y gstreamer
apt install -y gtypist
apt install -y guile-static
apt install -y guile
apt install -y gum
apt install -y gumbo-parser-static
apt install -y gumbo-parser
apt install -y gzip
apt install -y haproxy
apt install -y harfbuzz-icu
apt install -y harfbuzz-utils
apt install -y harfbuzz
apt install -y has
apt install -y hash-slinger
apt install -y hashdeep
apt install -y hcl
apt install -y hcloud
apt install -y helix-grammars
apt install -y helix
apt install -y helm-ls
apt install -y helm
apt install -y help2man
apt install -y hexcurse
apt install -y hexedit
apt install -y hexer
apt install -y hexyl
apt install -y heyu
apt install -y hfsutils
apt install -y hilbish
apt install -y hnterm
apt install -y hoedown-static
apt install -y hoedown
apt install -y hollywood
apt install -y hors
apt install -y hr
apt install -y hstr
apt install -y html-xml-utils
apt install -y html2text
apt install -y htop
apt install -y htslib-static
apt install -y htslib
apt install -y httping
apt install -y httrack-data
apt install -y httrack-static
apt install -y httrack
apt install -y hub
apt install -y hugo
apt install -y hummin
apt install -y hunspell-en-us
apt install -y hunspell-fr
apt install -y hunspell-hu
apt install -y hunspell-nl
apt install -y hunspell-ru
apt install -y hunspell-static
apt install -y hunspell
apt install -y hut
apt install -y hwdata
apt install -y hydroxide
apt install -y hyperfine
apt install -y hz
apt install -y i2pd-static
apt install -y i2pd
apt install -y icecast
apt install -y ices
apt install -y iconv
apt install -y icoutils
apt install -y icu-devtools
apt install -y id3lib-static
apt install -y id3lib
apt install -y id3ted
apt install -y id3v2
apt install -y imagemagick-static
apt install -y imagemagick
apt install -y imath
apt install -y imgflo
apt install -y imlib2-static
apt install -y imlib2
apt install -y indent
apt install -y inetutils
apt install -y influxdb
apt install -y innoextract
apt install -y inotify-tools-static
apt install -y inotify-tools
apt install -y intltool
apt install -y inxi
apt install -y ipcalc
apt install -y iperf3-static
apt install -y iperf3
apt install -y ipfs
apt install -y ipmitool
apt install -y iproute2
apt install -y ipv6calc
apt install -y ipv6toolkit
apt install -y ircd-irc2
apt install -y ired
apt install -y irssi
apt install -y isync
apt install -y iverilog-static
apt install -y iverilog
apt install -y iwyu
apt install -y jack-example-tools
apt install -y jack2
apt install -y jack
apt install -y janet
apt install -y jbig2dec-static
apt install -y jbig2dec
apt install -y jbig2enc-static
apt install -y jbig2enc
apt install -y jcal-static
apt install -y jcal
apt install -y jfrog-cli
apt install -y jftui
apt install -y jhead
apt install -y jigdo
apt install -y jira-go
apt install -y jo
apt install -y joe
apt install -y jove
apt install -y jp2a
apt install -y jpegoptim
apt install -y jq-lsp
apt install -y jq-static
apt install -y jq
apt install -y jql
apt install -y json-c-static
apt install -y json-c
apt install -y json-glib
apt install -y jsoncpp-static
apt install -y jsoncpp
apt install -y jump
apt install -y jupp
apt install -y just
apt install -y k2pdfopt
apt install -y k9s
apt install -y kainjow-mustache
apt install -y kakoune-lsp
apt install -y kakoune
apt install -y kbd
apt install -y kcptun
apt install -y keybase
apt install -y keychain
apt install -y kibi
apt install -y kiwix-tools
apt install -y knockd
apt install -y knot-utils
apt install -y kona
apt install -y kotlin
apt install -y krb5
apt install -y kubecolor
apt install -y kubectl
apt install -y kubelogin
apt install -y ladspa-sdk
apt install -y lame
apt install -y lastpass-cli
apt install -y lazygit
apt install -y lazyread
apt install -y lcal
apt install -y ldc
apt install -y ldd
apt install -y ldns-static
apt install -y ldns
apt install -y ledger
apt install -y leptonica-static
apt install -y leptonica
apt install -y less
apt install -y lesspipe
apt install -y leveldb
apt install -y lexbor
apt install -y lexter
apt install -y lf
apt install -y lftp-static
apt install -y lftp
apt install -y lgogdownloader
apt install -y lhasa-static
apt install -y lhasa
apt install -y liba52-static
apt install -y liba52
apt install -y libacl-static
apt install -y libacl
apt install -y libaml
apt install -y libandroid-complex-math
apt install -y libandroid-execinfo-static
apt install -y libandroid-execinfo
apt install -y libandroid-glob
apt install -y libandroid-posix-semaphore-static
apt install -y libandroid-posix-semaphore
apt install -y libandroid-selinux
apt install -y libandroid-shmem-static
apt install -y libandroid-shmem
apt install -y libandroid-spawn
apt install -y libandroid-stub
apt install -y libandroid-support
apt install -y libandroid-sysv-semaphore-static
apt install -y libandroid-sysv-semaphore
apt install -y libandroid-wordexp-static
apt install -y libandroid-wordexp
apt install -y libao-static
apt install -y libao
apt install -y libaom-static
apt install -y libaom
apt install -y libapt-pkg-perl
apt install -y libarchive-static
apt install -y libarchive
apt install -y libarrow-cpp
apt install -y libasio
apt install -y libasm-static
apt install -y libasm
apt install -y libass-static
apt install -y libass
apt install -y libassuan-static
apt install -y libassuan
apt install -y libatomic-ops-static
apt install -y libatomic-ops
apt install -y libbcprov-java
apt install -y libblkid
apt install -y libblocksruntime
apt install -y libblosc-static
apt install -y libblosc
apt install -y libbluray-static
apt install -y libbluray-utils
apt install -y libbluray
apt install -y libbs2b-static
apt install -y libbs2b
apt install -y libbsd-static
apt install -y libbsd
apt install -y libbullet
apt install -y libburn-static
apt install -y libburn
apt install -y libbz2
apt install -y libc++
apt install -y libc++utilities
apt install -y libc-client-static
apt install -y libc-client
apt install -y libcaca-static
apt install -y libcaca
apt install -y libcairo
apt install -y libcairomm-1.0
apt install -y libcairomm-1.16
apt install -y libcap-ng-static
apt install -y libcap-ng
apt install -y libcap-static
apt install -y libcap
apt install -y libccd
apt install -y libcddb-static
apt install -y libcddb
apt install -y libcdk
apt install -y libcec
apt install -y libceres-solver
apt install -y libchipmunk
apt install -y libcln-static
apt install -y libcln
apt install -y libcloog-static
apt install -y libcloog
apt install -y libcoap-static
apt install -y libcoap
apt install -y libcoinor-cgl-static
apt install -y libcoinor-cgl
apt install -y libcoinor-osi
apt install -y libcoinor-utils
apt install -y libcommons-lang3-java
apt install -y libcompiler-rt
apt install -y libconfig-static
apt install -y libconfig
apt install -y libconfuse-static
apt install -y libconfuse
apt install -y libcpufeatures
apt install -y libcroco-static
apt install -y libcroco
apt install -y libcrypt
apt install -y libcue
apt install -y libcunit-static
apt install -y libcunit
apt install -y libcurl-static
apt install -y libcurl
apt install -y libczmq-static
apt install -y libczmq
apt install -y libdaemon-static
apt install -y libdaemon
apt install -y libdart
apt install -y libdav1d
apt install -y libdb-static
apt install -y libdb
apt install -y libde265-static
apt install -y libde265
apt install -y libdebuginfod
apt install -y libdeflate-static
apt install -y libdeflate
apt install -y libdevil
apt install -y libdispatch
apt install -y libdisplay-info
apt install -y libdmtx-static
apt install -y libdmtx
apt install -y libdrm
apt install -y libduckdb-static
apt install -y libduckdb
apt install -y libduktape
apt install -y libdvbcsa-static
apt install -y libdvbcsa
apt install -y libdvbpsi-static
apt install -y libdvbpsi
apt install -y libdvdnav-static
apt install -y libdvdnav
apt install -y libdvdread-static
apt install -y libdvdread
apt install -y libdw-static
apt install -y libdw
apt install -y libebml
apt install -y libebur128
apt install -y libedit-static
apt install -y libedit
apt install -y libelf-static
apt install -y libelf
apt install -y libenet-static
apt install -y libenet
apt install -y libepoxy
apt install -y libev-static
apt install -y libev
apt install -y libevent
apt install -y libexif-static
apt install -y libexif
apt install -y libexpat-static
apt install -y libexpat
apt install -y libfann
apt install -y libfcl
apt install -y libfdisk
apt install -y libfdk-aac-static
apt install -y libfdk-aac
apt install -y libffi-static
apt install -y libffi
apt install -y libfixposix-static
apt install -y libfixposix
apt install -y libflac-static
apt install -y libflac
apt install -y libflann
apt install -y libforestdb
apt install -y libfreexl-static
apt install -y libfreexl
apt install -y libftxui
apt install -y libgc-static
apt install -y libgc
apt install -y libgcrypt-static
apt install -y libgcrypt
apt install -y libgd
apt install -y libgedit-gfls
apt install -y libgee-static
apt install -y libgee
apt install -y libgeos
apt install -y libgeotiff
apt install -y libgf2x-static
apt install -y libgf2x
apt install -y libgfshare-static
apt install -y libgfshare
apt install -y libgit2
apt install -y libglibmm-2.4
apt install -y libglibmm-2.68
apt install -y libglvnd-dev
apt install -y libglvnd
apt install -y libgmime-static
apt install -y libgmime
apt install -y libgmp-static
apt install -y libgmp
apt install -y libgnt
apt install -y libgnustep-base
apt install -y libgnutls-dane
apt install -y libgnutls-static
apt install -y libgnutls
apt install -y libgpg-error-static
apt install -y libgpg-error
apt install -y libgraphite
apt install -y libgrpc
apt install -y libgsasl-static
apt install -y libgsasl
apt install -y libgsf-static
apt install -y libgsf
apt install -y libgtop-static
apt install -y libgtop
apt install -y libgts-static
apt install -y libgts
apt install -y libgxps
apt install -y libhangul-static
apt install -y libhangul
apt install -y libhdf5-static
apt install -y libhdf5
apt install -y libheif-progs
apt install -y libheif
apt install -y libhiredis
apt install -y libhtmlcxx-static
apt install -y libhtmlcxx
apt install -y libhyphen-static
apt install -y libhyphen
apt install -y libical
apt install -y libice
apt install -y libiconv-static
apt install -y libiconv
apt install -y libicu-static
apt install -y libicu
apt install -y libid3tag
apt install -y libidn-static
apt install -y libidn2-static
apt install -y libidn2
apt install -y libidn
apt install -y libimagequant-static
apt install -y libimagequant
apt install -y libimobiledevice-glue-static
apt install -y libimobiledevice-glue
apt install -y libimobiledevice-static
apt install -y libimobiledevice
apt install -y libimtui
apt install -y libinih
apt install -y libiniparser-static
apt install -y libiniparser
apt install -y libiodbc-static
apt install -y libiodbc
apt install -y libisl-static
apt install -y libisl
apt install -y libisoburn-static
apt install -y libisoburn
apt install -y libisofs-static
apt install -y libisofs
apt install -y libjanet-static
apt install -y libjanet
apt install -y libjansi
apt install -y libjansson-static
apt install -y libjansson
apt install -y libjasper-utils
apt install -y libjasper
apt install -y libjpeg-turbo-progs
apt install -y libjpeg-turbo-static
apt install -y libjpeg-turbo
apt install -y libjxl-progs
apt install -y libjxl
apt install -y libkiwix
apt install -y libknot-static
apt install -y libknot
apt install -y libkokkos
apt install -y libksba-static
apt install -y libksba
apt install -y liblightning-static
apt install -y liblightning
apt install -y libliquid-dsp-static
apt install -y libliquid-dsp
apt install -y libllvm-static
apt install -y libllvm
apt install -y liblmdb-static
apt install -y liblmdb
apt install -y liblo-static
apt install -y liblo
apt install -y liblog4c-static
apt install -y liblog4c
apt install -y liblog4cxx
apt install -y liblqr-static
apt install -y liblqr
apt install -y liblrdf-static
apt install -y liblrdf
apt install -y libltdl
apt install -y liblua51-static
apt install -y liblua51
apt install -y liblua52-static
apt install -y liblua52
apt install -y liblua53-static
apt install -y liblua53
apt install -y liblua54-static
apt install -y liblua54
apt install -y libluajit-static
apt install -y libluajit
apt install -y liblz4
apt install -y liblzma-static
apt install -y liblzma
apt install -y liblzo-static
apt install -y liblzo
apt install -y libmaa
apt install -y libmad
apt install -y libmariadbcpp
apt install -y libmatio
apt install -y libmatroska
apt install -y libmaxminddb-static
apt install -y libmaxminddb-tools
apt install -y libmaxminddb
apt install -y libmcrypt-static
apt install -y libmcrypt
apt install -y libmd-static
apt install -y libmd
apt install -y libmdbx
apt install -y libmediainfo-static
apt install -y libmediainfo
apt install -y libmesode-static
apt install -y libmesode
apt install -y libmhash-static
apt install -y libmhash
apt install -y libmicrohttpd-static
apt install -y libmicrohttpd
apt install -y libminizip-ng
apt install -y libminizip-static
apt install -y libminizip
apt install -y libmnl-static
apt install -y libmnl
apt install -y libmodplug-static
apt install -y libmodplug
apt install -y libmosquitto
apt install -y libmount
apt install -y libmp3lame-static
apt install -y libmp3lame
apt install -y libmp3splt-static
apt install -y libmp3splt
apt install -y libmpc-static
apt install -y libmpc
apt install -y libmpdclient
apt install -y libmpeg2-static
apt install -y libmpeg2
apt install -y libmpfr-static
apt install -y libmpfr
apt install -y libmsgpack-cxx
apt install -y libmsgpack-static
apt install -y libmsgpack
apt install -y libmuparser
apt install -y libmypaint-static
apt install -y libmypaint
apt install -y libnats-c-static
apt install -y libnats-c
apt install -y libncnn-static
apt install -y libncnn
apt install -y libneon-static
apt install -y libneon
apt install -y libnet-static
apt install -y libnet
apt install -y libnettle-static
apt install -y libnettle
apt install -y libnewt-static
apt install -y libnewt
apt install -y libnfc-static
apt install -y libnfc
apt install -y libnfs
apt install -y libnftnl-static
apt install -y libnftnl
apt install -y libnghttp2-static
apt install -y libnghttp2
apt install -y libnghttp3-static
apt install -y libnghttp3
apt install -y libnl-cli-static
apt install -y libnl-cli
apt install -y libnl-static
apt install -y libnl
apt install -y libnova-static
apt install -y libnova
apt install -y libnpth-static
apt install -y libnpth
apt install -y libnspr-static
apt install -y libnspr
apt install -y libnss
apt install -y libntl-static
apt install -y libntl
apt install -y libobjc2
apt install -y libode
apt install -y libogg-static
apt install -y libogg
apt install -y liboggz-static
apt install -y liboggz
apt install -y libolm
apt install -y libopenblas-static
apt install -y libopenblas
apt install -y libopencc
apt install -y libopencore-amr-static
apt install -y libopencore-amr
apt install -y libopenfec
apt install -y libopenmpt-static
apt install -y libopenmpt
apt install -y libopus-static
apt install -y libopus
apt install -y libopusenc-static
apt install -y libopusenc
apt install -y liborc
apt install -y libosl-static
apt install -y libosl
apt install -y libosmium
apt install -y libotr-static
apt install -y libotr
apt install -y libowfat
apt install -y libp8-platform
apt install -y libpagmo
apt install -y libpangomm-1.4
apt install -y libpangomm-2.48
apt install -y libpano13-static
apt install -y libpano13
apt install -y libpaper-static
apt install -y libpaper
apt install -y libpcap-static
apt install -y libpcap
apt install -y libpcreposix
apt install -y libphysfs
apt install -y libpipeline-static
apt install -y libpipeline
apt install -y libpixman
apt install -y libplacebo
apt install -y libplist-static
apt install -y libplist
apt install -y libpluto-static
apt install -y libpluto
apt install -y libpng-static
apt install -y libpng
apt install -y libpngwriter-static
apt install -y libpngwriter
apt install -y libpoco
apt install -y libpolly
apt install -y libpopt-static
apt install -y libpopt
apt install -y libprotobuf-c-static
apt install -y libprotobuf-c
apt install -y libprotobuf
apt install -y libprotozero
apt install -y libpsl-static
apt install -y libpsl
apt install -y libpugixml
apt install -y libqrencode
apt install -y libraptor2-static
apt install -y libraptor2
apt install -y libraqm
apt install -y librasqal-static
apt install -y librasqal
apt install -y librav1e-static
apt install -y librav1e
apt install -y libraw-static
apt install -y libraw
apt install -y libre2
apt install -y libregexp-assemble-perl
apt install -y libresolv-wrapper
apt install -y libretls-static
apt install -y libretls
apt install -y librime
apt install -y librinutils
apt install -y librnnoise-static
apt install -y librnnoise
apt install -y librocksdb-static
apt install -y librocksdb
apt install -y librsvg
apt install -y librsync
apt install -y librtmidi
apt install -y librttopo-static
apt install -y librttopo
apt install -y librusty-v8
apt install -y libsamplerate
apt install -y libsasl-static
apt install -y libsasl
apt install -y libsass-static
apt install -y libsass
apt install -y libsearpc-static
apt install -y libsearpc
apt install -y libseat
apt install -y libseccomp-static
apt install -y libseccomp
apt install -y libsecp256k1-static
apt install -y libsecp256k1
apt install -y libsecret
apt install -y libsfdo
apt install -y libshout-static
apt install -y libshout
apt install -y libsigc++-2.0
apt install -y libsigc++-3.0
apt install -y libsignal-protocol-c
apt install -y libsigsegv-static
apt install -y libsigsegv
apt install -y libsixel
apt install -y libslirp
apt install -y libsm
apt install -y libsmartcols
apt install -y libsnappy
apt install -y libsndfile-static
apt install -y libsndfile
apt install -y libsodium-static
apt install -y libsodium
apt install -y libsoldout-static
apt install -y libsoldout
apt install -y libsophia-static
apt install -y libsophia
apt install -y libsoundtouch-static
apt install -y libsoundtouch
apt install -y libsoup3
apt install -y libsoup
apt install -y libsoxr
apt install -y libspatialindex
apt install -y libspatialite-static
apt install -y libspatialite
apt install -y libspdlog
apt install -y libspectre-static
apt install -y libspectre
apt install -y libspeex-static
apt install -y libspeex
apt install -y libspice-protocol
apt install -y libspice-server-static
apt install -y libspice-server
apt install -y libsqlite-static
apt install -y libsqlite-tcl
apt install -y libsqlite
apt install -y libsrt
apt install -y libssh2-static
apt install -y libssh2
apt install -y libssh
apt install -y libstemmer-static
apt install -y libstemmer
apt install -y libstrophe-static
apt install -y libstrophe
apt install -y libt3config
apt install -y libt3highlight
apt install -y libt3key
apt install -y libt3widget
apt install -y libt3window
apt install -y libtalloc-static
apt install -y libtalloc
apt install -y libtasn1-static
apt install -y libtasn1
apt install -y libtbb
apt install -y libtd-static
apt install -y libtd
apt install -y libtdb
apt install -y libtermkey
apt install -y libtheora-static
apt install -y libtheora
apt install -y libthread-db
apt install -y libtiff-static
apt install -y libtiff-utils
apt install -y libtiff
apt install -y libtiledb
apt install -y libtins
apt install -y libtinyxml2
apt install -y libtinyxml
apt install -y libtirpc-static
apt install -y libtirpc
apt install -y libtllist
apt install -y libtomcrypt-static
apt install -y libtomcrypt
apt install -y libtommath-static
apt install -y libtommath
apt install -y libtool
apt install -y libtorrent-rasterbar
apt install -y libtorrent-static
apt install -y libtorrent
apt install -y libtpms-static
apt install -y libtpms
apt install -y libtranscript
apt install -y libtree-ldd
apt install -y libtsduck-static
apt install -y libtsduck
apt install -y libtvision
apt install -y libtwolame-static
apt install -y libtwolame
apt install -y libuber-h3
apt install -y libuchardet-static
apt install -y libuchardet
apt install -y libucontext-static
apt install -y libucontext
apt install -y libudfread-static
apt install -y libudfread
apt install -y libunbound-static
apt install -y libunbound
apt install -y libunibilium
apt install -y libunistring-static
apt install -y libunistring
apt install -y libunqlite
apt install -y libupscaledb-static
apt install -y libupscaledb
apt install -y libusb-static
apt install -y libusb
apt install -y libusbmuxd-static
apt install -y libusbmuxd
apt install -y libusbredir
apt install -y libutf8-range
apt install -y libuuid
apt install -y libuv-static
apt install -y libuv
apt install -y libv4l-static
apt install -y libv4l
apt install -y libvbisam-static
apt install -y libvbisam
apt install -y libvidstab
apt install -y libvigra
apt install -y libvips
apt install -y libvmaf-static
apt install -y libvmaf
apt install -y libvo-amrwbenc-static
apt install -y libvo-amrwbenc
apt install -y libvoikko-static
apt install -y libvoikko
apt install -y libvorbis-static
apt install -y libvorbis
apt install -y libvpx-static
apt install -y libvpx
apt install -y libvterm
apt install -y libvxl
apt install -y libwavpack-static
apt install -y libwavpack
apt install -y libwayland-cross-scanner
apt install -y libwayland-protocols
apt install -y libwayland
apt install -y libwebp-static
apt install -y libwebp
apt install -y libwebrtc-audio-processing
apt install -y libwebsockets
apt install -y libwolfssl
apt install -y libwren
apt install -y libwslay
apt install -y libwv-static
apt install -y libwv
apt install -y libx11-static
apt install -y libx11
apt install -y libx264-static
apt install -y libx264
apt install -y libx265-static
apt install -y libx265
apt install -y libxapian-static
apt install -y libxapian
apt install -y libxau
apt install -y libxcb-static
apt install -y libxcb
apt install -y libxcfun
apt install -y libxdg-basedir-static
apt install -y libxdg-basedir
apt install -y libxdmcp-static
apt install -y libxdmcp
apt install -y libxdrfile
apt install -y libxext-static
apt install -y libxext
apt install -y libxfixes-static
apt install -y libxfixes
apt install -y libxft-static
apt install -y libxft
apt install -y libxi-static
apt install -y libxi
apt install -y libxls-static
apt install -y libxls
apt install -y libxlsxwriter
apt install -y libxml2-python-static
apt install -y libxml2-python
apt install -y libxml2-static
apt install -y libxml2-utils
apt install -y libxml2
apt install -y libxmlb
apt install -y libxmlrpc-static
apt install -y libxmlrpc
apt install -y libxrandr-static
apt install -y libxrandr
apt install -y libxrender
apt install -y libxslt
apt install -y libxss-static
apt install -y libxss
apt install -y libxt-static
apt install -y libxt
apt install -y libxtst-static
apt install -y libxtst
apt install -y libyaml-cpp
apt install -y libyaml-static
apt install -y libyaml
apt install -y libzen-static
apt install -y libzen
apt install -y libzim
apt install -y libzimg-static
apt install -y libzimg
apt install -y libzip
apt install -y libzita-convolver
apt install -y libzix
apt install -y libzmq-static
apt install -y libzmq
apt install -y libzopfli
apt install -y libzxing-cpp
apt install -y lighttpd
apt install -y lilv
apt install -y lilypond
apt install -y links
apt install -y lipl
apt install -y lit
apt install -y litespeedtest
apt install -y littlecms-static
apt install -y littlecms-utils
apt install -y littlecms
apt install -y llbuild
apt install -y lld
apt install -y lldb
apt install -y llvm-mingw-w64-libcompiler-rt
apt install -y llvm-mingw-w64-tools
apt install -y llvm-mingw-w64-ucrt
apt install -y llvm-mingw-w64
apt install -y llvm-tools
apt install -y llvm
apt install -y llvmgold
apt install -y lnav
apt install -y lnd
apt install -y locustdb
apt install -y logo-ls
apt install -y logrotate
apt install -y loksh
apt install -y lowdown-static
apt install -y lowdown
apt install -y lr
apt install -y lrzip
apt install -y lrzsz
apt install -y lsd
apt install -y lsix
apt install -y lsof-static
apt install -y lsof
apt install -y ltrace
apt install -y lua-language-server
apt install -y lua-lgi
apt install -y lua-lpeg
apt install -y lua51-lpeg
apt install -y lua51
apt install -y lua52-lpeg
apt install -y lua52
apt install -y lua53-lpeg
apt install -y lua53
apt install -y lua54
apt install -y luajit
apt install -y luarocks
apt install -y luv
apt install -y luvi
apt install -y luvit
apt install -y lux
apt install -y lv2
apt install -y lychee
apt install -y lynx
apt install -y lz4
apt install -y lzip
apt install -y lzlib-static
apt install -y lzlib
apt install -y lzop
apt install -y m4
apt install -y macchina
apt install -y magic-wormhole-rs
apt install -y mailsync
apt install -y mailutils-static
apt install -y mailutils
apt install -y make-guile
apt install -y make
apt install -y man
apt install -y mangal
apt install -y manim
apt install -y manpages
apt install -y mapserver
apt install -y mariadb-static
apt install -y mariadb
apt install -y marisa-static
apt install -y marisa
apt install -y markdown-flashcards
apt install -y mathomatic
apt install -y matplotlib
apt install -y matterbridge
apt install -y matterircd
apt install -y mautrix-whatsapp
apt install -y maven
apt install -y maxcso
apt install -y maxima
apt install -y mazter
apt install -y mbedtls-static
apt install -y mbedtls
apt install -y mc
apt install -y mcfly
apt install -y mdbook-epub
apt install -y mdbook-graphviz
apt install -y mdbook-katex
apt install -y mdbook-linkcheck
apt install -y mdbook-mermaid
apt install -y mdbook-open-on-gh
apt install -y mdbook-pikchr
apt install -y mdbook-plantuml
apt install -y mdbook-presentation-preprocessor
apt install -y mdbook-svgbob2
apt install -y mdbook-svgbob
apt install -y mdbook-tera
apt install -y mdbook-toc
apt install -y mdbook
apt install -y mdbtools-static
apt install -y mdbtools
apt install -y mdns-scan
apt install -y mdp
apt install -y media-types
apt install -y mediainfo
apt install -y mediamtx
apt install -y megacmd
apt install -y megatools
apt install -y memcached
apt install -y mercury-static
apt install -y mercury
apt install -y mesa-dev
apt install -y mesa-vulkan-icd-freedreno-dri3
apt install -y mesa-vulkan-icd-freedreno
apt install -y mesa-vulkan-icd-swrast
apt install -y mesa
apt install -y mfcuk
apt install -y mg
apt install -y micro
apt install -y microsocks
apt install -y miller
apt install -y mimetic-static
apt install -y mimetic
apt install -y minesweeper
apt install -y minicom
apt install -y minidlna
apt install -y miniflux
apt install -y minimodem
apt install -y minio
apt install -y miniserve
apt install -y minisign
apt install -y miniupnpc-static
apt install -y miniupnpc
apt install -y minizinc-static
apt install -y minizinc
apt install -y mkbootimg
apt install -y mkp224o
apt install -y mksh
apt install -y mktorrent
apt install -y mlir
apt install -y mlocate
apt install -y moar
apt install -y mold
apt install -y monero
apt install -y monetdb
apt install -y monolith
apt install -y moon-buggy
apt install -y moreutils
apt install -y moria
apt install -y morse2ascii
apt install -y mosh-perl
apt install -y mosh
apt install -y mosquitto
apt install -y most
apt install -y mount-utils
apt install -y mp3cat-go
apt install -y mp3cat
apt install -y mp3gain
apt install -y mp3splt
apt install -y mp3wrap
apt install -y mpc
apt install -y mpd
apt install -y mpdscribble
apt install -y mpg123-static
apt install -y mpg123
apt install -y mplayer
apt install -y mpv
apt install -y mruby-static
apt install -y mruby
apt install -y msmtp
apt install -y mtd-utils
apt install -y mtools
apt install -y mu
apt install -y muchsync
apt install -y multitail
apt install -y mupdf-static
apt install -y mupdf-tools
apt install -y mupdf
apt install -y music-file-organizer
apt install -y mutt
apt install -y mympd
apt install -y mypaint-brushes
apt install -y myrepos
apt install -y n-t-roff-sc
apt install -y n2n
apt install -y nala
apt install -y nali
apt install -y nano
apt install -y nasm
apt install -y natpmpc-static
apt install -y natpmpc
apt install -y navi
apt install -y navidrome
apt install -y ncdc
apt install -y ncdu
apt install -y ncftp
apt install -y ncmpcpp
apt install -y ncompress
apt install -y ncpamixer
apt install -y ncspot
apt install -y ncurses-static
apt install -y ncurses-ui-libs-static
apt install -y ncurses-ui-libs
apt install -y ncurses-utils
apt install -y ncurses
apt install -y ndk-multilib-native-static
apt install -y ndk-multilib-native-stubs
apt install -y ndk-multilib
apt install -y ndk-sysroot
apt install -y ne
apt install -y nelua
apt install -y neocmakelsp
apt install -y neofetch
apt install -y neomutt
apt install -y neovim
apt install -y nerdfix
apt install -y net-snmp-static
apt install -y net-snmp
apt install -y net-tools
apt install -y netcat-openbsd
apt install -y netcdf-c-static
apt install -y netcdf-c
apt install -y nethack
apt install -y netpbm
apt install -y netsed
apt install -y netstandard-targeting-pack-2.1-8.0
apt install -y netstandard-targeting-pack-2.1
apt install -y nettle
apt install -y newsboat
apt install -y nginx
apt install -y ngircd
apt install -y ngspice
apt install -y nim
apt install -y ninja
apt install -y ninvaders
apt install -y nlohmann-json
apt install -y nlopt
apt install -y nmap-ncat
apt install -y nmap
apt install -y nmh
apt install -y nmon
apt install -y nnn
apt install -y no-more-secrets
apt install -y nodejs-lts
apt install -y nodejs
apt install -y notcurses-data
apt install -y notcurses-tools
apt install -y notcurses
apt install -y notmuch
apt install -y npush
apt install -y nsis-stubs
apt install -y nsis
apt install -y nsnake
apt install -y nss-utils
apt install -y nudoku
apt install -y nushell
apt install -y nwipe
apt install -y nyancat
apt install -y nzbget
apt install -y o-editor
apt install -y oathtool-static
apt install -y oathtool
apt install -y obfs4proxy
apt install -y ocl-icd
apt install -y ocrad-static
apt install -y ocrad
apt install -y octave-static
apt install -y octave
apt install -y octomap-static
apt install -y octomap
apt install -y odt2txt
apt install -y oh-my-posh
apt install -y okc-agents
apt install -y ol
apt install -y oleo
apt install -y onefetch
apt install -y onigmo-static
apt install -y onigmo
apt install -y oniguruma-static
apt install -y oniguruma
apt install -y oorexx-static
apt install -y oorexx
apt install -y open-adventure
apt install -y openal-soft
apt install -y openbabel
apt install -y opencc-tools
apt install -y opencl-clhpp
apt install -y opencl-headers
apt install -y opencl-vendor-driver
apt install -y opencolorio
apt install -y openethereum-utils
apt install -y openethereum
apt install -y openexr
apt install -y openfoam
apt install -y opengl
apt install -y openh264
apt install -y openjdk-21-source
apt install -y openjdk-21-x
apt install -y openjdk-21
apt install -y openjpeg-tools
apt install -y openjpeg
apt install -y openldap-static
apt install -y openldap
apt install -y openmpi-static
apt install -y openmpi
apt install -y openscad
apt install -y openssh-sftp-server
apt install -y openssh
apt install -y openssl-static
apt install -y openssl-tool
apt install -y openssl
apt install -y optipng
apt install -y opus-tools
apt install -y opusfile-static
apt install -y opusfile
apt install -y osm2pgsql
apt install -y osmctools
apt install -y osmesa
apt install -y osmium-tool
apt install -y osslsigncode
apt install -y ossp-uuid-static
apt install -y ossp-uuid
apt install -y ovmf
apt install -y p11-kit
apt install -y p7zip
apt install -y pacman4console
apt install -y pacman
apt install -y panda3d-samples
apt install -y panda3d-static
apt install -y panda3d
apt install -y pandoc
apt install -y pango
apt install -y paperkey
apt install -y par2
apt install -y parallel
apt install -y pari-static
apt install -y pari
apt install -y parted-static
apt install -y parted
apt install -y paruz
apt install -y pass-otp
apt install -y pass
apt install -y passphrase2pgp
apt install -y pastebinit
apt install -y pastel
apt install -y patch
apt install -y patchelf
apt install -y pathpicker
apt install -y pb
apt install -y pcal
apt install -y pcaudiolib-static
apt install -y pcaudiolib
apt install -y pcre-static
apt install -y pcre2-static
apt install -y pcre2
apt install -y pcre2grep
apt install -y pcre
apt install -y pcregrep
apt install -y pdf2djvu
apt install -y pdf2svg
apt install -y pdfcpu
apt install -y pdfgrep
apt install -y pdftk
apt install -y peaclock
apt install -y peco
apt install -y perl-rename
apt install -y perl
apt install -y pet
apt install -y pforth
apt install -y pgroonga
apt install -y photon-rss
apt install -y php-apache-ldap
apt install -y php-apache-opcache
apt install -y php-apache-pgsql
apt install -y php-apache-sodium
apt install -y php-apache
apt install -y php-apcu
apt install -y php-fpm
apt install -y php-gd
apt install -y php-imagick
apt install -y php-ldap
apt install -y php-pgsql
apt install -y php-psr
apt install -y php-redis
apt install -y php-sodium
apt install -y php-zephir-parser
apt install -y php
apt install -y phpmyadmin
apt install -y pianobar
apt install -y pick
apt install -y picocom
apt install -y picolisp
apt install -y pigz
apt install -y pika
apt install -y pinentry
apt install -y pingme
apt install -y pipebuffer
apt install -y pipes-sh
apt install -y pipewire
apt install -y pkg-config
apt install -y pkgfile
apt install -y pkgtop
apt install -y plantuml
apt install -y play-audio
apt install -y plutolang
apt install -y plzip
apt install -y pngcrush
apt install -y pngquant
apt install -y pocketbase
apt install -y poke-static
apt install -y poke
apt install -y polipo
apt install -y polyml-static
apt install -y polyml
apt install -y pomodoro-curses
apt install -y poppler-data
apt install -y poppler
apt install -y portaudio-static
apt install -y portaudio
apt install -y portmidi
apt install -y posixvala
apt install -y postgis
apt install -y postgresql-static
apt install -y postgresql
apt install -y potrace-static
apt install -y potrace
apt install -y pounce
apt install -y povray-data
apt install -y povray
apt install -y predict
apt install -y privoxy
apt install -y procps-static
apt install -y procps
apt install -y procs
apt install -y procyon-decompiler
apt install -y profanity
apt install -y progress
apt install -y proj
apt install -y proot-distro
apt install -y proot
apt install -y protobuf-dev
apt install -y protobuf-static
apt install -y protobuf
apt install -y proton-bridge
apt install -y prover9
apt install -y proxmark3
apt install -y proxychains-ng
apt install -y psmisc
apt install -y ptex-static
apt install -y ptex
apt install -y ptunnel-ng
apt install -y pueue
apt install -y pulseaudio-glib
apt install -y pulseaudio
apt install -y pup
apt install -y pure-ftpd
apt install -y pv
apt install -y pwgen
apt install -y pycairo
apt install -y pygobject
apt install -y pystring
apt install -y python-apsw
apt install -y python-apt
apt install -y python-bcrypt
apt install -y python-contourpy
apt install -y python-cryptography
apt install -y python-ensurepip-wheels
apt install -y python-greenlet
apt install -y python-grpcio
apt install -y python-lameenc
apt install -y python-libsass
apt install -y python-lxml
apt install -y python-msgpack
apt install -y python-numpy-static
apt install -y python-numpy
apt install -y python-onnxruntime
apt install -y python-pillow
apt install -y python-pip
apt install -y python-pyarrow
apt install -y python-pynvim
apt install -y python-sabyenc3
apt install -y python-scipy-static
apt install -y python-scipy
apt install -y python-skia-pathops
apt install -y python-static
apt install -y python-tflite-runtime
apt install -y python-tldp
apt install -y python-torch-static
apt install -y python-torch
apt install -y python-torchaudio
apt install -y python-torchvision
apt install -y python-xcbgen
apt install -y python-xlib
apt install -y python2-static
apt install -y python2
apt install -y python
apt install -y pyunbound
apt install -y pzstd
apt install -y q-dns-client
apt install -y qalc-static
apt install -y qalc
apt install -y qemu-common
apt install -y qemu-system-aarch64-headless
apt install -y qemu-system-arm-headless
apt install -y qemu-system-i386-headless
apt install -y qemu-system-m68k-headless
apt install -y qemu-system-ppc-headless
apt install -y qemu-system-ppc64-headless
apt install -y qemu-system-riscv32-headless
apt install -y qemu-system-riscv64-headless
apt install -y qemu-system-x86-64-headless
apt install -y qemu-user-aarch64
apt install -y qemu-user-arm
apt install -y qemu-user-i386
apt install -y qemu-user-m68k
apt install -y qemu-user-ppc64
apt install -y qemu-user-ppc
apt install -y qemu-user-riscv32
apt install -y qemu-user-riscv64
apt install -y qemu-user-x86-64
apt install -y qemu-utils
apt install -y qhull-static
apt install -y qhull
apt install -y qpdf-static
apt install -y qpdf
apt install -y qrsspig
apt install -y qrupdate-ng
apt install -y quick-lint-js
apt install -y quickjs
apt install -y quilt
apt install -y rabbitmq-server
apt install -y racket-static
apt install -y racket
apt install -y radare2
apt install -y rage
apt install -y ragel-static
apt install -y ragel
apt install -y railway-cli
apt install -y range-v3
apt install -y ranger
apt install -y rapidjson
apt install -y rappel
apt install -y ratt
apt install -y rav1e
apt install -y ravencoin-static
apt install -y ravencoin
apt install -y rbw
apt install -y rc
apt install -y rclone
apt install -y rcm
apt install -y rcs
apt install -y rdfind
apt install -y rdiff-backup
apt install -y rdiff
apt install -y rdircd
apt install -y rdrview
apt install -y re2c
apt install -y readline-static
apt install -y readline
apt install -y recode-static
apt install -y recode
apt install -y recoll-python
apt install -y recoll
apt install -y recutils-static
apt install -y recutils
apt install -y redir
apt install -y redis
apt install -y remind
apt install -y renameutils
apt install -y reptyr
apt install -y resolv-conf
apt install -y restic-server
apt install -y restic
apt install -y restish
apt install -y rgbds
apt install -y rhash-static
apt install -y rhash
apt install -y rig
apt install -y rinetd
apt install -y rip2
apt install -y ripgrep-all
apt install -y ripgrep
apt install -y ripsecrets
apt install -y rirc
apt install -y rizin
apt install -y rlwrap
apt install -y rnr
apt install -y robin-map
apt install -y robotfindskitten
apt install -y root-repo
apt install -y roqet
apt install -y rp-pppoe
apt install -y rpm
apt install -y rq
apt install -y rsgain
apt install -y rsnapshot
apt install -y rsync
apt install -y rtmpdump-static
apt install -y rtmpdump
apt install -y rtorrent
apt install -y rubberband-ladspa
apt install -y rubberband-lv2
apt install -y rubberband-static
apt install -y rubberband-vamp
apt install -y rubberband
apt install -y rubiks-cube
apt install -y ruby-ri
apt install -y ruby
apt install -y ruff
apt install -y runit-static
apt install -y runit
apt install -y rush
apt install -y rust-analyzer
apt install -y rust-bindgen
apt install -y rust-docs
apt install -y rust-src
apt install -y rust-std-aarch64-linux-android
apt install -y rust-std-armv7-linux-androideabi
apt install -y rust-std-i686-linux-android
apt install -y rust-std-wasm32-unknown-unknown
apt install -y rust-std-wasm32-wasip1
apt install -y rust-std-wasm32-wasip2
apt install -y rust-std-x86-64-linux-android
apt install -y rust
apt install -y rustc-dev
apt install -y rustc-src
apt install -y rustscan
apt install -y rw
apt install -y rxfetch
apt install -y sabnzbd
apt install -y salty-chat
apt install -y samba
apt install -y samefile
apt install -y samurai
apt install -y sassc
apt install -y sc-im
apt install -y scala
apt install -y scc
apt install -y sccache
apt install -y scdaemon
apt install -y scdoc
apt install -y screen
apt install -y screenfetch
apt install -y scrub
apt install -y scrypt
apt install -y sd
apt install -y sdcv
apt install -y seafile-client-static
apt install -y seafile-client
apt install -y seanime
apt install -y seccure
apt install -y secure-delete
apt install -y sed
apt install -y sendxmpp
apt install -y senpai
apt install -y sensible-utils
apt install -y serd
apt install -y serf-static
apt install -y serf
apt install -y sfeed
apt install -y sftpgo
apt install -y shaderc
apt install -y shairport-sync
apt install -y sharutils
apt install -y shc
apt install -y sheldon
apt install -y shell2http
apt install -y shellharden
apt install -y shellinabox
apt install -y shfmt
apt install -y shiori
apt install -y shntool
apt install -y shtool
apt install -y signify
apt install -y silicon
apt install -y silversearcher-ag
apt install -y simde
apt install -y simdjson
apt install -y simh
apt install -y simulavr
apt install -y simuwaerm
apt install -y sing-box
apt install -y skate
apt install -y sl
apt install -y slang
apt install -y slashtime
apt install -y sleuthkit-static
apt install -y sleuthkit
apt install -y slides
apt install -y slugify
apt install -y smalltalk-static
apt install -y smalltalk
apt install -y snake
apt install -y snapcast-client
apt install -y snapcast-server
apt install -y snmptt
apt install -y snowflake-client
apt install -y snowflake-proxy
apt install -y snowflake
apt install -y socat
apt install -y softether-vpn
apt install -y soju
apt install -y solidity
apt install -y sops
apt install -y sord
apt install -y sox-static
apt install -y sox
apt install -y spatialite-tools
apt install -y speechd-data
apt install -y speechd
apt install -y speedtest-go
apt install -y speex-utils
apt install -y speexdsp-static
apt install -y speexdsp
apt install -y spglib
apt install -y spiped
apt install -y spirv-headers
apt install -y spirv-tools
apt install -y sqlcipher-static
apt install -y sqlcipher
apt install -y sqlite
apt install -y squashfs-tools-ng-static
apt install -y squashfs-tools-ng
apt install -y squeezelite
apt install -y squid
apt install -y sratom
apt install -y srelay
apt install -y srt-tools
apt install -y srt2vobsub
apt install -y ssdb
apt install -y ssdeep-static
apt install -y ssdeep
apt install -y sse2neon
apt install -y sshpass
apt install -y sshping
apt install -y sslscan
apt install -y sssnake
apt install -y ssss
apt install -y stag
apt install -y starship
apt install -y stdman
apt install -y stdoutisatty
apt install -y steghide
apt install -y stemwords
apt install -y step-cli
apt install -y stfl-static
apt install -y stfl
apt install -y stoken-static
apt install -y stoken
apt install -y stone
apt install -y storj-uplink
apt install -y stow
apt install -y strace
apt install -y streamripper
apt install -y stunnel-static
apt install -y stunnel
apt install -y stuntman
apt install -y stylua
apt install -y subtitleripper
apt install -y subversion-perl-static
apt install -y subversion-perl
apt install -y subversion-static
apt install -y subversion
apt install -y suil
apt install -y suite3270
apt install -y suitesparse-static
apt install -y suitesparse
apt install -y sun
apt install -y sundials-static
apt install -y sundials
apt install -y surfraw
apt install -y svt-av1
apt install -y swaks
apt install -y swi-prolog
apt install -y swiftshader
apt install -y swig
apt install -y swtpm-static
apt install -y swtpm
apt install -y syncthing
apt install -y sysprop
apt install -y taglib
apt install -y taplo
apt install -y tar
apt install -y task-spooler
apt install -y tasksh
apt install -y taskwarrior
apt install -y tcc
apt install -y tcl
apt install -y tcllib
apt install -y tcsh
apt install -y tdb-tools
apt install -y tdl
apt install -y tea
apt install -y tealdeer
apt install -y teckit-static
apt install -y teckit
apt install -y tectonic
apt install -y telegram-bot-api
apt install -y telegram-cli
apt install -y teleport-tsh
apt install -y tenki-php
apt install -y tere
apt install -y tergent
apt install -y termimage
apt install -y termplay
apt install -y termux-am
apt install -y termux-api-static
apt install -y termux-api
apt install -y termux-apt-repo
apt install -y termux-auth
apt install -y termux-create-package
apt install -y termux-elf-cleaner
apt install -y termux-exec
apt install -y termux-gui-bash
apt install -y termux-gui-c
apt install -y termux-gui-package
apt install -y termux-gui-pm
apt install -y termux-keyring
apt install -y termux-licenses
apt install -y termux-services
apt install -y termux-tools
apt install -y teseq
apt install -y tesseract
apt install -y testssl-sh
apt install -y tex-gyre
apt install -y texinfo
apt install -y texlab
apt install -y texlive-bin-static
apt install -y texlive-bin
apt install -y texlive-installer
apt install -y thrift
apt install -y tidy-static
apt install -y tidy
apt install -y tig
apt install -y tilde
apt install -y time
apt install -y timewarrior
apt install -y timg
apt install -y timidity++
apt install -y tin-summer
apt install -y tintin++
apt install -y tinyfugue
apt install -y tinygo-common
apt install -y tinygo
apt install -y tinymist
apt install -y tinyproxy
apt install -y tinyscheme
apt install -y tizonia
apt install -y tk
apt install -y tmate
apt install -y tmux
apt install -y toilet
apt install -y tokei
apt install -y tome2
apt install -y toml11
apt install -y topgrade
apt install -y tor
apt install -y torchaudio-ffmpeg
apt install -y torsocks-static
apt install -y torsocks
apt install -y totem-pl-parser
apt install -y toxic
apt install -y tracepath
apt install -y traceroute
apt install -y translate-shell
apt install -y transmission
apt install -y tree-sitter-c
apt install -y tree-sitter-lua-static
apt install -y tree-sitter-lua
apt install -y tree-sitter-markdown-static
apt install -y tree-sitter-markdown
apt install -y tree-sitter-parsers
apt install -y tree-sitter-query-static
apt install -y tree-sitter-query
apt install -y tree-sitter-static
apt install -y tree-sitter-vim-static
apt install -y tree-sitter-vim
apt install -y tree-sitter-vimdoc-static
apt install -y tree-sitter-vimdoc
apt install -y tree-sitter
apt install -y tree
apt install -y trojan-go
apt install -y trurl
apt install -y trzsz-go
apt install -y trzsz-ssh
apt install -y tsduck-java
apt install -y tsduck-plugins
apt install -y tsduck-python
apt install -y tsduck-tools
apt install -y tsmuxer
apt install -y tsocks
apt install -y tsu
apt install -y ttf-dejavu
apt install -y tty-clock
apt install -y tty-solitaire
apt install -y ttyc
apt install -y ttyd
apt install -y ttyper
apt install -y ttyplot
apt install -y ttyrec
apt install -y tur-repo
apt install -y tut
apt install -y tvheadend-data
apt install -y tvheadend
apt install -y tweego
apt install -y twolame
apt install -y typst
apt install -y typstfmt
apt install -y uchardet
apt install -y udftools
apt install -y uftrace
apt install -y ugit
apt install -y ugrep
apt install -y unar
apt install -y unbound
apt install -y unicode-data
apt install -y unicorn-static
apt install -y unicorn
apt install -y apt install -y unifdef
apt install -y units-cur
apt install -y units
apt install -y unpaper
apt install -y unrar
apt install -y unshield
apt install -y unzip
apt install -y up
apt install -y update-info-dir
apt install -y upscaledb-tools
apt install -y upx
apt install -y urdfdom-headers
apt install -y urdfdom
apt install -y usql
apt install -y utf8cpp
apt install -y utf8proc-static
apt install -y utf8proc
apt install -y utfdecode
apt install -y uthash
apt install -y util-linux-static
apt install -y util-linux
apt install -y uucp
apt install -y uuid-utils
apt install -y uv
apt install -y uwsgi
apt install -y v2ray
apt install -y valac-static
apt install -y valac
apt install -y valadoc-static
apt install -y valadoc
apt install -y vale
apt install -y vamp-plugin-sdk-static
apt install -y vamp-plugin-sdk
apt install -y vbindiff
apt install -y vcsh
apt install -y vde2-static
apt install -y vde2
apt install -y vegeta
apt install -y vera
apt install -y vgmstream
apt install -y vgmtools
apt install -y viddy
apt install -y vifm
apt install -y vile
apt install -y vim
apt install -y virglrenderer-android
apt install -y virglrenderer
apt install -y virustotal-cli
apt install -y vis
apt install -y vitetris
apt install -y viu
apt install -y vivid
apt install -y vlc-static
apt install -y vlc
apt install -y vobsub2srt
apt install -y vorbis-tools
apt install -y vtm
apt install -y vttest
apt install -y vtutils
apt install -y vulkan-extension-layer
apt install -y vulkan-headers
apt install -y vulkan-loader-android
apt install -y vulkan-loader-generic
apt install -y vulkan-loader
apt install -y vulkan-tools
apt install -y vulkan-utility-libraries
apt install -y vulkan-validation-layers
apt install -y vulkan-volk
apt install -y w3m
apt install -y wabt
apt install -y wakatime-cli
apt install -y walk
apt install -y wasi-libc
apt install -y wasm-component-ld
apt install -y wasmedge
apt install -y wasmer
apt install -y wasmtime
apt install -y watchexec
apt install -y wavpack
apt install -y waypipe
apt install -y wcalc
apt install -y wdiff
apt install -y webp-pixbuf-loader
apt install -y websocat
apt install -y websocketd
apt install -y weechat-lua-plugin
apt install -y weechat-matrix-rs
apt install -y weechat-perl-plugin
apt install -y weechat-python-plugin
apt install -y weechat-ruby-plugin
apt install -y weechat
apt install -y weggli
apt install -y wego
apt install -y wget2-static
apt install -y wget2
apt install -y wget
apt install -y wgetpaste
apt install -y which
apt install -y whiptail
apt install -y whitebox-tools
apt install -y whois
apt install -y wireguard-tools
apt install -y wireproxy
apt install -y wiz
apt install -y woff2
apt install -y wol
apt install -y wordgrinder
apt install -y wren
apt install -y wrk
apt install -y wtfutil
apt install -y wuzz
apt install -y wv-tools
apt install -y x11-repo
apt install -y x264
x265
apt install -y xapian-tools
apt install -y xcb-proto
apt install -y xdelta3
apt install -y xh
apt install -y xls2csv
apt install -y xmake
apt install -y xmlsec-static
apt install -y xmlsec
apt install -y xmlstarlet
apt install -y xmlto
apt install -y xmppc
apt install -y xorg-util-macros
apt install -y xorgproto
apt install -y xorriso
apt install -y xpup
apt install -y xsltproc
apt install -y xtrans
apt install -y xvidcore-static
apt install -y xvidcore
apt install -y xxd
apt install -y xxhash-static
apt install -y xxhash
apt install -y xz-utils
apt install -y yadm
apt install -y yajl-static
apt install -y yajl
apt install -y yara-static
apt install -y yara
apt install -y yarn
apt install -y yasm-static
apt install -y yasm
apt install -y yazi
apt install -y yosys
apt install -y youtubedr
apt install -y yq
apt install -y ytfzf
apt install -y ytui-music
apt install -y yuma123-static
apt install -y yuma123
apt install -y z-push
apt install -y z3
apt install -y zbar-static
apt install -y zbar
apt install -y zellij

apt install -y zip
apt install -y zipios
apt install -y zk
apt install -y zlib-static
apt install -y zlib
apt install -y znc
apt install -y zola
apt install -y zopfli
apt install -y zoxide
apt install -y zpaq
apt install -y zrok
apt install -y zsh-completions
apt install -y zsh
apt install -y zssh
apt install -y zstd
apt install -y zsync
apt install -y zziplib
apt install -y zzuf-static
apt install -y zzuf

apt install -y tcsh
apt install -y tdb-tools
apt install -y tdl
apt install -y tea
apt install -y tealdeer
apt install -y teckit-static
apt install -y teckit
apt install -y tectonic
apt install -y telegram-bot-api
apt install -y telegram-cli
apt install -y telepathy-glib-static
apt install -y telepathy-glib
apt install -y teleport-tsh
apt install -y tenki-phpc
apt install -y tere
apt install -y tergent
apt install -y termimage
apt install -y termplay
apt install -y termshark
apt install -y termux-am-socket
apt install -y termux-am
apt install -y termux-api-static
apt install -y termux-api
apt install -y termux-apt-repo
apt install -y termux-auth
apt install -y termux-create-package
apt install -y termux-elf-cleaner
apt install -y termux-exec
apt install -y termux-gui-bash
apt install -y termux-gui-c
apt install -y termux-gui-package
apt install -y termux-gui-pm
apt install -y termux-keyring
apt install -y termux-licenses
apt install -y termux-services
apt install -y termux-tools
apt install -y termux-x11-nightly
apt install -y teseq
apt install -y tesseract
apt install -y testdisk
apt install -y testssl.sh
apt install -y tex-gyre
apt install -y texinfo
apt install -y texlab
apt install -y texlive-bin-static
apt install -y texlive-bin
apt install -y texlive-installer
apt install -y texstudio-data
apt install -y texstudio
apt install -y texworks
